#!/usr/bin/env bash

create-symlink() {
  local source=$1
  local target=$2

  if [[ -L "$target" ]]; then
    unlink "$target"
  fi
  if [[ -f "$target" ]]; then
    echo "File exists: $target" >&2
    return 1
  fi

  if [[ ! -d $(dirname -- "$target") ]]; then
    mkdir -p -- "$(dirname -- "$target")"
  fi

  ln -s -- "$(cd "$(dirname -- "$source")" && pwd)/$(basename -- "$source")" "$target"
}

install() {
  local home=$HOME
  local xdgconfig=${XDG_CONFIG_HOME:-$HOME/.config}
  local xdgdata=${XDG_DATA_HOME:-$HOME/.local/share}

  # git
  create-symlink ./config/git "$xdgconfig/git"
  # zsh
  create-symlink ./config/zsh/.zshenv "$home/.zshenv"
  create-symlink ./config/zsh "$xdgconfig/zsh"
  # antidote
  rm -rf -- "$xdgdata/antidote"
  git clone --depth 1 https://github.com/mattmc3/antidote "$xdgdata/antidote"
  # vim
  create-symlink ./config/vim "$home/.vim"
  # nvim
  create-symlink ./config/nvim "$xdgconfig/nvim"
  # tmux
  create-symlink ./config/tmux "$xdgconfig/tmux"
  # tpm
  rm -rf -- "$xdgdata/tpm/plugins"
  git clone --depth 1 https://github.com/tmux-plugins/tpm "$xdgdata/tpm/plugins"
  # mise (fzf もここで入れる)
  create-symlink ./config/mise "$xdgconfig/mise"
  if command -v mise >/dev/null; then
    mise install
  fi
}

install
